name: Pokédex CI

on:
  push:
    branches: ["master-pokeapi"]
  pull_request:
    branches: ["master-pokeapi"]

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        continue-on-error: true
        run: |
          docker run -it --rm \
              --name "pokedex-$(date +%Y%m%d-%H%M%S)" \
              --mount type=bind,source="${curr_dir}/pokedex/data",target=/app/pokedex/data \
              veekun/pokedex setup -v
      - name: Dump Pokédex
        continue-on-error: true
        run: |
          bin/docker-pokedex dump -l all
      - name: Print log
        run: |
          cat bin/docker-pokedex.log

  Python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run Setup
        run: |
          pokedex setup
      - name: Dump DB
        run: |
          pokedex dump -l all
